# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_auto_20160723_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'ordering': ['score']},
        ),
        migrations.RemoveField(
            model_name='name',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='name',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='name',
            table='Names',
        ),
    ]
